# Generated by Django 3.1.5 on 2021-01-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itemtype', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Кол-во'),
        ),
    ]
