# Generated by Django 3.1.5 on 2021-02-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210124_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ткань')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткань',
            },
        ),
        migrations.CreateModel(
            name='ItemModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1c', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID 1C')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модификация')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификация',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID 1C'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_items', to='api.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID 1C'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='modification_id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Модификации 1C'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес товара в г.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='api.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='api.itemmaterial', verbose_name='Ткань'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='api.itemmodification', verbose_name='Модификация'),
        ),
    ]
