# Generated by Django 3.1.5 on 2021-02-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210204_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='image_thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='images/catalog/items/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='api.category', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='ItemAtStore',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
