# Generated by Django 3.1.5 on 2021-02-07 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210207_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название типа доставки')),
                ('time', models.CharField(max_length=255, null=True, verbose_name='Минимальное время доставки')),
                ('price', models.CharField(max_length=255, null=True, verbose_name='Минимальная стоимость доставки')),
            ],
            options={
                'verbose_name': 'Тип доставки',
                'verbose_name_plural': 'Типы доставки',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название города')),
                ('name_lower', models.CharField(editable=False, max_length=255, null=True, verbose_name='Название города')),
                ('price', models.IntegerField(null=True, verbose_name='Стоимость доставки')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.deliverytype', verbose_name='Относится к ')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
