# Generated by Django 3.1.5 on 2021-02-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_city_deliverytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': '1. Категории'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': '3. Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Базовый товар', 'verbose_name_plural': '4. Базовые товары'},
        ),
        migrations.AlterModelOptions(
            name='itemcolor',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': '5.3. Цвета'},
        ),
        migrations.AlterModelOptions(
            name='itemheight',
            options={'verbose_name': 'Рост', 'verbose_name_plural': '5.2. Рост'},
        ),
        migrations.AlterModelOptions(
            name='itemmaterial',
            options={'verbose_name': 'Ткань', 'verbose_name_plural': '5.4. Ткань'},
        ),
        migrations.AlterModelOptions(
            name='itemmodification',
            options={'verbose_name': 'Модификация', 'verbose_name_plural': '5.5. Модификация'},
        ),
        migrations.AlterModelOptions(
            name='itemsize',
            options={'verbose_name': 'Размер', 'verbose_name_plural': '5.1. Размеры'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'verbose_name': 'Вид товара', 'verbose_name_plural': '5. Виды товаров'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промо код', 'verbose_name_plural': '6. Промо коды'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': '2. Подкатегории'},
        ),
        migrations.AddField(
            model_name='cart',
            name='raw_price',
            field=models.IntegerField(default=0),
        ),
    ]
