# Generated by Django 3.1.5 on 2021-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210207_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
