# Generated by Django 3.1.5 on 2021-02-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Цена без скидки'),
        ),
        migrations.AddField(
            model_name='itemcolor',
            name='id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID 1C'),
        ),
        migrations.AddField(
            model_name='itemheight',
            name='id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID 1C'),
        ),
        migrations.AddField(
            model_name='itemmaterial',
            name='id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID 1C'),
        ),
        migrations.AddField(
            model_name='itemsize',
            name='id_1c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID 1C'),
        ),
    ]
