# Generated by Django 3.1.5 on 2021-02-21 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('api', '0016_auto_20210221_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'ordering': ('-is_self_delivery',), 'verbose_name': 'Тип доставки', 'verbose_name_plural': 'Типы доставки'},
        ),
        migrations.CreateModel(
            name='PaymentObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа')),
                ('pay_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид платежа')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус платежа')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Сумма платежа')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.guest', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
