# Generated by Django 3.1.5 on 2021-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_cdekkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdekkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
