# Generated by Django 3.1.5 on 2021-02-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cdekkey_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='code',
            field=models.CharField(max_length=255, null=True, verbose_name='Код доставки для CRM'),
        ),
        migrations.AlterField(
            model_name='city',
            name='price',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
