# Generated by Django 3.1.5 on 2021-02-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210225_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytype',
            name='is_office_cdek',
            field=models.BooleanField(default=False, verbose_name='Это СДЕК до офиса?'),
        ),
        migrations.AlterField(
            model_name='city',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.deliverytype', verbose_name='Относится к'),
        ),
        migrations.CreateModel(
            name='CdekOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID офиса')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес офиса')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='api.city', verbose_name='Относится к')),
            ],
            options={
                'verbose_name': 'Адрес офиса',
                'verbose_name_plural': 'Адреса офисов СДЕК',
            },
        ),
    ]
