# Generated by Django 3.1.5 on 2021-02-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210227_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdekoffice',
            options={'verbose_name': 'Адрес офиса', 'verbose_name_plural': '7.2. Адреса офисов СДЕК'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': '7.1. Города'},
        ),
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'ordering': ('-is_self_delivery',), 'verbose_name': 'Тип доставки', 'verbose_name_plural': '7. Типы доставки'},
        ),
        migrations.RemoveField(
            model_name='paymentobj',
            name='pay_code',
        ),
        migrations.AddField(
            model_name='paymentobj',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AlterField(
            model_name='paymentobj',
            name='pay_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа yandex'),
        ),
    ]
