# Generated by Django 3.1.5 on 2021-02-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210227_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0),
        ),
    ]
