# Generated by Django 3.1.5 on 2021-03-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_order_delivery_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemheight',
            options={'ordering': ('-name',), 'verbose_name': 'Рост', 'verbose_name_plural': '5.2. Рост'},
        ),
        migrations.AlterModelOptions(
            name='itemsize',
            options={'ordering': ('-name',), 'verbose_name': 'Размер', 'verbose_name_plural': '5.1. Размеры'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, db_index=True, to='api.CartItem', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
