# Generated by Django 3.1.5 on 2021-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_collection_is_base_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsize',
            name='order_num',
            field=models.IntegerField(default=100, verbose_name='Номер по порядку'),
        ),
    ]
