# Generated by Django 3.1.5 on 2021-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210302_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='order_num',
            field=models.IntegerField(default=100, verbose_name='Номер по порядку'),
        ),
    ]
