# Generated by Django 3.1.5 on 2021-03-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_collection_name_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='string',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст в бегущей строке'),
        ),
    ]
