# Generated by Django 3.1.5 on 2021-03-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_category_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_at_home',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
