# Generated by Django 3.1.5 on 2021-04-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210407_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='is_preview',
            field=models.BooleanField(default=False, verbose_name='Это превью'),
        ),
    ]
