# Generated by Django 3.1.5 on 2021-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_itemimage_is_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='bar_cade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Штрихкод'),
        ),
    ]
