# Generated by Django 3.1.5 on 2021-05-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_itemtype_bar_cade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_val',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='old_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена без скидки'),
        ),
    ]
