# Generated by Django 3.1.5 on 2021-05-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210504_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order_num',), 'verbose_name': 'Базовый товар', 'verbose_name_plural': '4. Базовые товары'},
        ),
        migrations.AddField(
            model_name='item',
            name='recommended_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subcategory', verbose_name='Подкатегория для рекомендуемых товаров'),
        ),
    ]
