# Generated by Django 3.1.5 on 2021-06-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_order_is_need_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='h1',
            field=models.TextField(blank=True, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='h1',
            field=models.TextField(blank=True, null=True, verbose_name='H1'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
    ]
