# Generated by Django 3.1.5 on 2021-06-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210617_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentobj',
            name='ya_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа yandex'),
        ),
        migrations.AlterField(
            model_name='paymentobj',
            name='pay_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа '),
        ),
    ]
