# Generated by Django 3.1.5 on 2021-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20210620_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.IntegerField(blank=True, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': '0.Подписка на рассылку',
            },
        ),
    ]
