# Generated by Django 3.1.5 on 2021-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_mailsubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsubscribe',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
