# Generated by Django 3.1.5 on 2021-06-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210623_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='is_first',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Первый ?'),
        ),
    ]
