# Generated by Django 3.1.5 on 2021-07-17 08:26

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20210713_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/catalog/items/', verbose_name='Изображение цвета'),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True, verbose_name='Цвет'),
        ),
    ]
